project:
  type: website
  execute-dir: file

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu: 
        - text: "1. Layered Grammar of Graphics: ggplot2"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "2. Beyond ggplot2 Fundamentals"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "3a. Interactive Data Visualization"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
        - text: "3b. Animated Statistical Graphics"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"
        - text: "4a. Visualizing Distribution"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html"
        - text: "4b. Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"
        - text: "4c. Visualising Uncertainty"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
        - text: "4d. Building Funnel Plot"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html"
        - text: "5a. Creating Ternary Plot with R"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html"
        - text: "5b. Visual Correlation Analysis"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html"
        - text: "5c. Visual Multivariate Analysis with Heatmap"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.html"
        - text: "5d. Visual Multivariate Analysis with Parallel Coordinates Plot"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.html"
        - text: "5e. Treemap Visualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.html"
    - text: "In-class Exercises"
      href: "In-class_Ex/In-class_Ex.html"
    - text: "Take-home Exercises"
      menu:
        - text: "Take-home Exercise 1"
        - href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    toc: true

editor: visual

